// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMM.Public.Data;

#nullable disable

namespace OMM.Public.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827085400_AddMasterDataSchema")]
    partial class AddMasterDataSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OMM.Public.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CountryName_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName_ZH_CN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName_ZH_TW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefaultCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "MY",
                            CountryName_EN = "Malaysia",
                            CountryName_ZH_CN = "Malaysia",
                            CountryName_ZH_TW = "Malaysia",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultCurrencyCode = "MYR",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeName_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeName_ZH_CN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeName_ZH_TW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Exchange", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExchangeCode = "BURSA",
                            ExchangeName_EN = "Bursa Malaysia",
                            ExchangeName_ZH_CN = "Bursa Malaysia",
                            ExchangeName_ZH_TW = "Bursa Malaysia",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InstitutionCategory")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName_ZH_CN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName_ZH_TW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Institution", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstitutionCategory = 0,
                            InstitutionCode = "MAYBANK",
                            InstitutionName_EN = "Maybank",
                            InstitutionName_ZH_CN = "Maybank",
                            InstitutionName_ZH_TW = "Maybank",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstitutionCategory = 0,
                            InstitutionCode = "CIMB",
                            InstitutionName_EN = "CIMB",
                            InstitutionName_ZH_CN = "CIMB",
                            InstitutionName_ZH_TW = "CIMB",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstitutionCategory = 0,
                            InstitutionCode = "PUBLIC-BANK",
                            InstitutionName_EN = "Public Bank",
                            InstitutionName_ZH_CN = "Public Bank",
                            InstitutionName_ZH_TW = "Public Bank",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstitutionCategory = 2,
                            InstitutionCode = "KWSP",
                            InstitutionName_EN = "KWSP",
                            InstitutionName_ZH_CN = "KWSP",
                            InstitutionName_ZH_TW = "KWSP",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstitutionCategory = 5,
                            InstitutionCode = "BURSA",
                            InstitutionName_EN = "Bursa Malaysia",
                            InstitutionName_ZH_CN = "Bursa Malaysia",
                            InstitutionName_ZH_TW = "Bursa Malaysia",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketName_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketName_ZH_CN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketName_ZH_TW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Market", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExchangeId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            MarketCode = "MAIN",
                            MarketName_EN = "Main Market",
                            MarketName_ZH_CN = "Main Market",
                            MarketName_ZH_TW = "Main Market"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExchangeId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            MarketCode = "ACE",
                            MarketName_EN = "ACE Market",
                            MarketName_ZH_CN = "ACE Market",
                            MarketName_ZH_TW = "ACE Market"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExchangeId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            MarketCode = "LEAP",
                            MarketName_EN = "LEAP Market",
                            MarketName_ZH_CN = "LEAP Market",
                            MarketName_ZH_TW = "LEAP Market"
                        });
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorName_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorName_ZH_CN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorName_ZH_TW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Sector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "FIN-SVC",
                            SectorName_EN = "Financial Services",
                            SectorName_ZH_CN = "Financial Services",
                            SectorName_ZH_TW = "Financial Services"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "CONSUMER",
                            SectorName_EN = "Consumer Products & Services",
                            SectorName_ZH_CN = "Consumer Products & Services",
                            SectorName_ZH_TW = "Consumer Products & Services"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "INDUSTRIAL",
                            SectorName_EN = "Industrial Products & Services",
                            SectorName_ZH_CN = "Industrial Products & Services",
                            SectorName_ZH_TW = "Industrial Products & Services"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "TECH",
                            SectorName_EN = "Technology",
                            SectorName_ZH_CN = "Technology",
                            SectorName_ZH_TW = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "TEL-MEDIA",
                            SectorName_EN = "Telecommunications & Media",
                            SectorName_ZH_CN = "Telecommunications & Media",
                            SectorName_ZH_TW = "Telecommunications & Media"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "HEALTH",
                            SectorName_EN = "Health Care",
                            SectorName_ZH_CN = "Health Care",
                            SectorName_ZH_TW = "Health Care"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "PROPERTY",
                            SectorName_EN = "Property",
                            SectorName_ZH_CN = "Property",
                            SectorName_ZH_TW = "Property"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "REIT",
                            SectorName_EN = "Real Estate Investment Trusts (REITs)",
                            SectorName_ZH_CN = "Real Estate Investment Trusts (REITs)",
                            SectorName_ZH_TW = "Real Estate Investment Trusts (REITs)"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "PLANTATION",
                            SectorName_EN = "Plantation",
                            SectorName_ZH_CN = "Plantation",
                            SectorName_ZH_TW = "Plantation"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "ENERGY",
                            SectorName_EN = "Energy",
                            SectorName_ZH_CN = "Energy",
                            SectorName_ZH_TW = "Energy"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "CONSTRUCTION",
                            SectorName_EN = "Construction",
                            SectorName_ZH_CN = "Construction",
                            SectorName_ZH_TW = "Construction"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "TRANSPORT",
                            SectorName_EN = "Transportation & Logistics",
                            SectorName_ZH_CN = "Transportation & Logistics",
                            SectorName_ZH_TW = "Transportation & Logistics"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorCode = "UTILITIES",
                            SectorName_EN = "Utilities",
                            SectorName_ZH_CN = "Utilities",
                            SectorName_ZH_TW = "Utilities"
                        });
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DebtToEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastCalculatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastScrapedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LegalName_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalName_ZH_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalName_ZH_TW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("NTA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ROA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ROE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RicCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<bool>("ShariahCompliant")
                        .HasColumnType("bit");

                    b.Property<string>("ShortName_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName_ZH_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName_ZH_TW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubSectorId")
                        .HasColumnType("int");

                    b.Property<string>("YahooSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("MarketId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SectorId");

                    b.HasIndex("SubSectorId");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.SubSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("SubSectorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSectorName_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSectorName_ZH_CN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSectorName_ZH_TW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SectorId");

                    b.ToTable("SubSector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 1,
                            SubSectorCode = "BANKING",
                            SubSectorName_EN = "Banking",
                            SubSectorName_ZH_CN = "Banking",
                            SubSectorName_ZH_TW = "Banking"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 1,
                            SubSectorCode = "INSURANCE",
                            SubSectorName_EN = "Insurance",
                            SubSectorName_ZH_CN = "Insurance",
                            SubSectorName_ZH_TW = "Insurance"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 1,
                            SubSectorCode = "OTHER-FIN",
                            SubSectorName_EN = "Other Financial Services",
                            SubSectorName_ZH_CN = "Other Financial Services",
                            SubSectorName_ZH_TW = "Other Financial Services"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 2,
                            SubSectorCode = "FOOD-BEV",
                            SubSectorName_EN = "Food & Beverages",
                            SubSectorName_ZH_CN = "Food & Beverages",
                            SubSectorName_ZH_TW = "Food & Beverages"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 2,
                            SubSectorCode = "RETAILERS",
                            SubSectorName_EN = "Retailers",
                            SubSectorName_ZH_CN = "Retailers",
                            SubSectorName_ZH_TW = "Retailers"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 2,
                            SubSectorCode = "AUTOMOTIVE",
                            SubSectorName_EN = "Automotive",
                            SubSectorName_ZH_CN = "Automotive",
                            SubSectorName_ZH_TW = "Automotive"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 2,
                            SubSectorCode = "CONSUMER-SVC",
                            SubSectorName_EN = "Consumer Services",
                            SubSectorName_ZH_CN = "Consumer Services",
                            SubSectorName_ZH_TW = "Consumer Services"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 2,
                            SubSectorCode = "HOUSEHOLD",
                            SubSectorName_EN = "Household Goods",
                            SubSectorName_ZH_CN = "Household Goods",
                            SubSectorName_ZH_TW = "Household Goods"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 2,
                            SubSectorCode = "AGRI",
                            SubSectorName_EN = "Agricultural Products",
                            SubSectorName_ZH_CN = "Agricultural Products",
                            SubSectorName_ZH_TW = "Agricultural Products"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 2,
                            SubSectorCode = "TRAVEL",
                            SubSectorName_EN = "Travel Leisure & Hospitality",
                            SubSectorName_ZH_CN = "Travel Leisure & Hospitality",
                            SubSectorName_ZH_TW = "Travel Leisure & Hospitality"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 3,
                            SubSectorCode = "BUILDING",
                            SubSectorName_EN = "Building Materials",
                            SubSectorName_ZH_CN = "Building Materials",
                            SubSectorName_ZH_TW = "Building Materials"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 3,
                            SubSectorCode = "CHEMICALS",
                            SubSectorName_EN = "Chemicals",
                            SubSectorName_ZH_CN = "Chemicals",
                            SubSectorName_ZH_TW = "Chemicals"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 3,
                            SubSectorCode = "METALS",
                            SubSectorName_EN = "Metals",
                            SubSectorName_ZH_CN = "Metals",
                            SubSectorName_ZH_TW = "Metals"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 3,
                            SubSectorCode = "PACKAGING",
                            SubSectorName_EN = "Packaging Materials",
                            SubSectorName_ZH_CN = "Packaging Materials",
                            SubSectorName_ZH_TW = "Packaging Materials"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 3,
                            SubSectorCode = "DIVERSIFIED",
                            SubSectorName_EN = "Diversified Industrials",
                            SubSectorName_ZH_CN = "Diversified Industrials",
                            SubSectorName_ZH_TW = "Diversified Industrials"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 3,
                            SubSectorCode = "IND-ENGINEERING",
                            SubSectorName_EN = "Industrial Engineering",
                            SubSectorName_ZH_CN = "Industrial Engineering",
                            SubSectorName_ZH_TW = "Industrial Engineering"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 4,
                            SubSectorCode = "SEMICONDUCTORS",
                            SubSectorName_EN = "Semiconductors",
                            SubSectorName_ZH_CN = "Semiconductors",
                            SubSectorName_ZH_TW = "Semiconductors"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 4,
                            SubSectorCode = "SOFTWARE",
                            SubSectorName_EN = "Software",
                            SubSectorName_ZH_CN = "Software",
                            SubSectorName_ZH_TW = "Software"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 4,
                            SubSectorCode = "DIGITAL",
                            SubSectorName_EN = "Digital Services",
                            SubSectorName_ZH_CN = "Digital Services",
                            SubSectorName_ZH_TW = "Digital Services"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 4,
                            SubSectorCode = "HARDWARE",
                            SubSectorName_EN = "Hardware",
                            SubSectorName_ZH_CN = "Hardware",
                            SubSectorName_ZH_TW = "Hardware"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 5,
                            SubSectorCode = "TELCO-SVC",
                            SubSectorName_EN = "Telecommunications Service Providers",
                            SubSectorName_ZH_CN = "Telecommunications Service Providers",
                            SubSectorName_ZH_TW = "Telecommunications Service Providers"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 5,
                            SubSectorCode = "MEDIA",
                            SubSectorName_EN = "Media & Advertising",
                            SubSectorName_ZH_CN = "Media & Advertising",
                            SubSectorName_ZH_TW = "Media & Advertising"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 5,
                            SubSectorCode = "TELCO-EQUIP",
                            SubSectorName_EN = "Telecommunications Equipment",
                            SubSectorName_ZH_CN = "Telecommunications Equipment",
                            SubSectorName_ZH_TW = "Telecommunications Equipment"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 6,
                            SubSectorCode = "HEALTHCARE",
                            SubSectorName_EN = "Healthcare Providers",
                            SubSectorName_ZH_CN = "Healthcare Providers",
                            SubSectorName_ZH_TW = "Healthcare Providers"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 6,
                            SubSectorCode = "PHARMA",
                            SubSectorName_EN = "Pharmaceuticals",
                            SubSectorName_ZH_CN = "Pharmaceuticals",
                            SubSectorName_ZH_TW = "Pharmaceuticals"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 6,
                            SubSectorCode = "HEALTH-EQUIP",
                            SubSectorName_EN = "Healthcare Equipment & Supplies",
                            SubSectorName_ZH_CN = "Healthcare Equipment & Supplies",
                            SubSectorName_ZH_TW = "Healthcare Equipment & Supplies"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 7,
                            SubSectorCode = "PROPERTY-DEV",
                            SubSectorName_EN = "Property Development",
                            SubSectorName_ZH_CN = "Property Development",
                            SubSectorName_ZH_TW = "Property Development"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 7,
                            SubSectorCode = "PROPERTY-INV",
                            SubSectorName_EN = "Property Investment & Management",
                            SubSectorName_ZH_CN = "Property Investment & Management",
                            SubSectorName_ZH_TW = "Property Investment & Management"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 8,
                            SubSectorCode = "COMMERCIAL",
                            SubSectorName_EN = "Commercial",
                            SubSectorName_ZH_CN = "Commercial",
                            SubSectorName_ZH_TW = "Commercial"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 8,
                            SubSectorCode = "RETAIL",
                            SubSectorName_EN = "Retail",
                            SubSectorName_ZH_CN = "Retail",
                            SubSectorName_ZH_TW = "Retail"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 8,
                            SubSectorCode = "INDUSTRIAL",
                            SubSectorName_EN = "Industrial",
                            SubSectorName_ZH_CN = "Industrial",
                            SubSectorName_ZH_TW = "Industrial"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 8,
                            SubSectorCode = "HOSPITALITY",
                            SubSectorName_EN = "Hospitality",
                            SubSectorName_ZH_CN = "Hospitality",
                            SubSectorName_ZH_TW = "Hospitality"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 8,
                            SubSectorCode = "HEALTHCARE-REIT",
                            SubSectorName_EN = "Healthcare",
                            SubSectorName_ZH_CN = "Healthcare",
                            SubSectorName_ZH_TW = "Healthcare"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 9,
                            SubSectorCode = "UPSTREAM",
                            SubSectorName_EN = "Upstream Plantation",
                            SubSectorName_ZH_CN = "Upstream Plantation",
                            SubSectorName_ZH_TW = "Upstream Plantation"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 9,
                            SubSectorCode = "INTEGRATED",
                            SubSectorName_EN = "Integrated Cultivation",
                            SubSectorName_ZH_CN = "Integrated Cultivation",
                            SubSectorName_ZH_TW = "Integrated Cultivation"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 10,
                            SubSectorCode = "OIL-GAS-PROD",
                            SubSectorName_EN = "Oil & Gas Producers",
                            SubSectorName_ZH_CN = "Oil & Gas Producers",
                            SubSectorName_ZH_TW = "Oil & Gas Producers"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 10,
                            SubSectorCode = "OIL-GAS-EQUIP",
                            SubSectorName_EN = "Oil & Gas Equipment & Services",
                            SubSectorName_ZH_CN = "Oil & Gas Equipment & Services",
                            SubSectorName_ZH_TW = "Oil & Gas Equipment & Services"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 10,
                            SubSectorCode = "RENEWABLE",
                            SubSectorName_EN = "Renewable Energy",
                            SubSectorName_ZH_CN = "Renewable Energy",
                            SubSectorName_ZH_TW = "Renewable Energy"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 11,
                            SubSectorCode = "CIVIL",
                            SubSectorName_EN = "Civil Engineering",
                            SubSectorName_ZH_CN = "Civil Engineering",
                            SubSectorName_ZH_TW = "Civil Engineering"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 11,
                            SubSectorCode = "HEAVY",
                            SubSectorName_EN = "Heavy Construction",
                            SubSectorName_ZH_CN = "Heavy Construction",
                            SubSectorName_ZH_TW = "Heavy Construction"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 11,
                            SubSectorCode = "SPECIALISED",
                            SubSectorName_EN = "Specialised Construction",
                            SubSectorName_ZH_CN = "Specialised Construction",
                            SubSectorName_ZH_TW = "Specialised Construction"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 12,
                            SubSectorCode = "LOGISTICS",
                            SubSectorName_EN = "Logistics Services",
                            SubSectorName_ZH_CN = "Logistics Services",
                            SubSectorName_ZH_TW = "Logistics Services"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 12,
                            SubSectorCode = "PORTS",
                            SubSectorName_EN = "Ports & Shipping",
                            SubSectorName_ZH_CN = "Ports & Shipping",
                            SubSectorName_ZH_TW = "Ports & Shipping"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 12,
                            SubSectorCode = "AIRLINES",
                            SubSectorName_EN = "Airlines & Aviation",
                            SubSectorName_ZH_CN = "Airlines & Aviation",
                            SubSectorName_ZH_TW = "Airlines & Aviation"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 12,
                            SubSectorCode = "ROAD-RAIL",
                            SubSectorName_EN = "Road & Rail",
                            SubSectorName_ZH_CN = "Road & Rail",
                            SubSectorName_ZH_TW = "Road & Rail"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 13,
                            SubSectorCode = "ELECTRICITY",
                            SubSectorName_EN = "Electricity",
                            SubSectorName_ZH_CN = "Electricity",
                            SubSectorName_ZH_TW = "Electricity"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            SectorId = 13,
                            SubSectorCode = "GAS-WATER",
                            SubSectorName_EN = "Gas & Water Distribution",
                            SubSectorName_ZH_CN = "Gas & Water Distribution",
                            SubSectorName_ZH_TW = "Gas & Water Distribution"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Country", b =>
                {
                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Exchange", b =>
                {
                    b.HasOne("OMM.Public.Models.MasterData.Country", "Country")
                        .WithMany("Exchanges")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Institution", b =>
                {
                    b.HasOne("OMM.Public.Models.MasterData.Country", "Country")
                        .WithMany("Institutions")
                        .HasForeignKey("CountryId");

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Market", b =>
                {
                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Models.MasterData.Exchange", "Exchange")
                        .WithMany("Markets")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Sector", b =>
                {
                    b.HasOne("OMM.Public.Models.MasterData.Country", "Country")
                        .WithMany("Sectors")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Stock", b =>
                {
                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Models.MasterData.Market", "Market")
                        .WithMany("Stocks")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Models.MasterData.Sector", "Sector")
                        .WithMany("Stocks")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Models.MasterData.SubSector", "SubSector")
                        .WithMany("Stocks")
                        .HasForeignKey("SubSectorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Market");

                    b.Navigation("Sector");

                    b.Navigation("SubSector");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.SubSector", b =>
                {
                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OMM.Public.Models.MasterData.Sector", "Sector")
                        .WithMany("SubSectors")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Country", b =>
                {
                    b.Navigation("Exchanges");

                    b.Navigation("Institutions");

                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Exchange", b =>
                {
                    b.Navigation("Markets");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Market", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.Sector", b =>
                {
                    b.Navigation("Stocks");

                    b.Navigation("SubSectors");
                });

            modelBuilder.Entity("OMM.Public.Models.MasterData.SubSector", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
